"""Windows installer finalizer.

Generates an NSIS .nsi script next to the archive. On a Win build host with
makensis on PATH this gets compiled to .exe; otherwise we leave the .nsi
in place so a CI worker can finish.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

NSIS_TEMPLATE = """; Auto-generated by chayuan_packager
!include "MUI2.nsh"
Name "Chayuan AI Platform {version} ({release})"
OutFile "{archive_stem}.exe"
InstallDir "$LOCALAPPDATA\\Chayuan"
RequestExecutionLevel user

Section "Install"
  SetOutPath "$INSTDIR"
  File "/oname=payload.tar.zst" "{archive_name}"
  ; bundled bootstrapper extracts payload.tar.zst (ships in vendor/)
  ExecWait '"$INSTDIR\\vendor\\runtimes\\python\\python.exe" -m chayuan_packager.installer payload.tar.zst'
  CreateShortCut "$DESKTOP\\Chayuan.lnk" "$INSTDIR\\Chayuan.exe"
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\\payload.tar.zst"
  RMDir /r "$INSTDIR"
  Delete "$DESKTOP\\Chayuan.lnk"
SectionEnd
"""


def finalize(*, archive: Path, version: str, release: str) -> Path:
    nsi = archive.with_suffix("").with_suffix(".nsi")
    nsi.write_text(
        NSIS_TEMPLATE.format(
            version=version,
            release=release,
            archive_stem=archive.stem,
            archive_name=archive.name,
        ),
        encoding="utf-8",
    )
    if shutil.which("makensis"):
        subprocess.run(["makensis", str(nsi)], check=False)
    return nsi
