"""Framework wiring —— "下载完一个模型 → 运行时立刻可见" 的桥梁。

历史空洞
========

下载模型只是把权重落到 ``<CHAYUAN_ROOT>/models/<category>/<repo>/`` 目录;
但 Ollama / vLLM / ComfyUI 等运行时要求权重在它们各自的目录约定下:

* **Ollama**     需要 ``Modelfile`` + ``ollama create`` 注册到本地 registry
                 (二进制需在 PATH 中)
* **HF 缓存族**  (vLLM / Infinity / sentence-transformers) 走 HuggingFace
                 cache 协议: ``~/.cache/huggingface/hub/models--<owner>--<name>/snapshots/<rev>/``
* **ComfyUI**    需要软链到 ``comfyui/models/{checkpoints,vae,clip,upscale_models}/``
* **llama.cpp**  ``./models/`` 找 GGUF;给个软链就行
* **whisper.cpp**``./models/ggml-*.bin`` 命名约定

每个运行时各有自己的"导入"步骤,本模块按 ``target_runtime`` 分发到具体
``_wire_<runtime>`` 实现,统一返回 :class:`WireOutcome`。

设计原则
========

* **声明式**: 加新运行时只需在 ``_WIRE_TABLE`` 加一行 +
  写 ``_wire_<runtime>`` 函数;不动 lifecycle。
* **失败安全**: 任何环节失败返回 ``ok=False``;调用方(lifecycle.WIRE 阶段)
  负责 rollback 已下载文件。
* **跨平台**: 软链不可用的 Windows 走拷贝;``which`` 失败时 fall back 到
  环境变量配置(避免硬依赖二进制在 PATH)。
* **幂等**: 同一模型重复 wire 不报错(已存在则跳过)。

注册到 lifecycle
================

模块加载时通过 ``register_wire_impl(wire)`` 把本模块的 :func:`wire` 函数注入
``chayuan_modelmgr.lifecycle``。详见 :func:`install_into_lifecycle`。
"""
from __future__ import annotations

import logging
import os
import platform
import shutil
import subprocess
from pathlib import Path
from typing import Callable, Dict, Optional, Tuple

logger = logging.getLogger("chayuan_runtime.framework_wiring")


# 复用 lifecycle 的 WireOutcome 类型;不直接 import 避免循环依赖,只在
# install_into_lifecycle 时才碰它。
class WireOutcome:  # noqa: D401 - 只是占位 / 同形 dataclass
    def __init__(self, ok: bool, runtime: str, detail: str = "", **extra) -> None:
        self.ok = ok
        self.runtime = runtime
        self.detail = detail
        self.extra: Dict[str, object] = dict(extra)


# ---------------------------------------------------------------------------
# 工具函数
# ---------------------------------------------------------------------------

def _is_windows() -> bool:
    return platform.system().lower() == "windows"


def _safe_link_or_copy(src: Path, dst: Path) -> str:
    """优先软链;不可用时拷贝。返回 'symlink' / 'copy' / 'skip'(目标已存在)。"""
    if dst.exists():
        return "skip"
    dst.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.symlink(src, dst, target_is_directory=src.is_dir())
        return "symlink"
    except (OSError, NotImplementedError):
        # Windows 没开发者模式时无法创建符号链接;退化为拷贝
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)
        return "copy"


def _which(bin_name: str) -> Optional[str]:
    """``shutil.which`` 的薄包装,Windows 自动加 .exe / .bat 变体。"""
    p = shutil.which(bin_name)
    if p:
        return p
    if _is_windows():
        for ext in (".exe", ".cmd", ".bat"):
            p = shutil.which(bin_name + ext)
            if p:
                return p
    return None


def _list_gguf(model_path: Path) -> list[Path]:
    return list(model_path.rglob("*.gguf"))


def _list_safetensors(model_path: Path) -> list[Path]:
    return list(model_path.rglob("*.safetensors"))


def _list_ckpt(model_path: Path) -> list[Path]:
    return list(model_path.rglob("*.ckpt")) + list(model_path.rglob("*.pt"))


# ---------------------------------------------------------------------------
# 各运行时 wire 实现
# ---------------------------------------------------------------------------

def _wire_ollama(model_path: Path, capability: str) -> WireOutcome:
    """Ollama: 写 Modelfile + ``ollama create``。

    优先找 GGUF 文件 (单文件) 作为 ``FROM``;若没找到 GGUF (说明是 HF safetensors
    格式),只能告诉用户"需要先转 GGUF"——本函数不做权重格式转换(超出范围)。
    """
    if capability not in ("chat", "embedding"):
        return WireOutcome(ok=True, runtime="ollama",
                           detail=f"capability={capability} 与 Ollama 不匹配,跳过")

    bin_path = _which("ollama")
    if not bin_path:
        return WireOutcome(
            ok=False, runtime="ollama",
            detail="未找到 ollama 二进制;请先安装 Ollama (https://ollama.com)",
            installable=True,
        )

    ggufs = _list_gguf(model_path)
    if not ggufs:
        return WireOutcome(
            ok=False, runtime="ollama",
            detail=(
                "目录中未找到 .gguf 文件;Ollama 仅支持 GGUF 格式。"
                "请先用 llama.cpp/convert_hf_to_gguf.py 转换,或选择已有 GGUF 镜像。"
            ),
            convert_hint="llama.cpp:convert_hf_to_gguf.py",
        )
    main_gguf = max(ggufs, key=lambda p: p.stat().st_size)

    # Modelfile 名约定: 用 repo 末段小写 + tag latest
    model_name = model_path.name.replace("/", "-").lower()
    modelfile_path = model_path / "Modelfile"
    modelfile_text = (
        f"# auto-generated by chayuan_runtime.framework_wiring\n"
        f"FROM {main_gguf}\n"
    )
    modelfile_path.write_text(modelfile_text, encoding="utf-8")

    try:
        proc = subprocess.run(
            [bin_path, "create", model_name, "-f", str(modelfile_path)],
            capture_output=True, text=True, timeout=180,
        )
    except subprocess.TimeoutExpired:
        return WireOutcome(ok=False, runtime="ollama", detail="ollama create 超时 (180s)")
    if proc.returncode != 0:
        return WireOutcome(
            ok=False, runtime="ollama",
            detail=f"ollama create 失败: {proc.stderr.strip() or proc.stdout.strip()}",
        )
    return WireOutcome(
        ok=True, runtime="ollama",
        detail=f"已注册 ollama:{model_name}",
        ollama_name=model_name,
        gguf_path=str(main_gguf),
    )


def _wire_hf_cache(model_path: Path, capability: str) -> WireOutcome:
    """HF 缓存族: vLLM / Infinity / sentence-transformers / transformers 通用。

    HF 缓存约定:
        ~/.cache/huggingface/hub/
            models--<owner>--<name>/
                snapshots/<rev>/   <- 软链到 model_path
                blobs/             <- 实际权重 blob (不动)
                refs/main          <- 文本文件,内容是 rev 名

    简化版: 直接把 model_path 当作 snapshot 软链入 hub 目录,
    refs/main 写"main",blobs 不需要 (HF 客户端读 snapshot 即可)。
    """
    hf_home = Path(os.environ.get("HF_HOME") or os.path.expanduser("~/.cache/huggingface"))
    hub_root = hf_home / "hub"
    # repo_id 推断: model_path 的目录名通常就是 ``Owner/Name``,
    # 但 model_dir_for 可能转成 ``Owner__Name`` 或 ``Owner-Name``;
    # 我们用最稳妥的方式:从 manifest 读;读不到就用 model_path.name
    repo_id = _read_repo_id_from_manifest(model_path) or model_path.name
    if "/" not in repo_id:
        # 没有 owner 段; HF 客户端会按 ``models--<repo>`` 找
        slug = f"models--{repo_id}"
    else:
        owner, name = repo_id.split("/", 1)
        slug = f"models--{owner}--{name}"

    hub_dir = hub_root / slug
    snapshot_dir = hub_dir / "snapshots" / "main"
    refs_dir = hub_dir / "refs"
    refs_dir.mkdir(parents=True, exist_ok=True)
    (refs_dir / "main").write_text("main", encoding="utf-8")

    action = _safe_link_or_copy(model_path, snapshot_dir)
    return WireOutcome(
        ok=True, runtime="hf-cache",
        detail=f"hf-cache 已 {action} 到 {snapshot_dir}",
        hf_cache_dir=str(snapshot_dir),
        repo_id=repo_id,
    )


def _wire_vllm(model_path: Path, capability: str) -> WireOutcome:
    """vLLM: 走 HF cache (因为 vLLM serve 接受 ``--model <repo_id>``,
    会从 HF cache 读)。本函数等价于 _wire_hf_cache。
    """
    out = _wire_hf_cache(model_path, capability)
    out.runtime = "vllm"
    return out


def _wire_infinity(model_path: Path, capability: str) -> WireOutcome:
    out = _wire_hf_cache(model_path, capability)
    out.runtime = "infinity"
    return out


def _wire_llamacpp(model_path: Path, capability: str) -> WireOutcome:
    """llama.cpp: 在 chayuan_data/llamacpp/models/ 下软链 GGUF。

    llama.cpp server 启动时用 ``-m <path>``;给个稳定符号链接路径方便管理。
    """
    ggufs = _list_gguf(model_path)
    if not ggufs:
        return WireOutcome(
            ok=False, runtime="llamacpp",
            detail="未找到 .gguf 文件;llama.cpp 仅支持 GGUF",
        )
    main_gguf = max(ggufs, key=lambda p: p.stat().st_size)
    target_root = _llamacpp_models_dir()
    target = target_root / main_gguf.name
    action = _safe_link_or_copy(main_gguf, target)
    return WireOutcome(
        ok=True, runtime="llamacpp",
        detail=f"llama.cpp 已 {action} 到 {target}",
        gguf_path=str(target),
    )


def _wire_whispercpp(model_path: Path, capability: str) -> WireOutcome:
    """whisper.cpp: 软链到 ``ggml-*.bin`` 命名空间。"""
    bins = list(model_path.rglob("ggml-*.bin"))
    if not bins:
        # 退而求其次,任何 .bin 都行
        bins = list(model_path.rglob("*.bin"))
    if not bins:
        return WireOutcome(
            ok=False, runtime="whispercpp",
            detail="未找到 ggml-*.bin;whisper.cpp 仅支持 ggml 格式",
        )
    target_root = _whispercpp_models_dir()
    main = max(bins, key=lambda p: p.stat().st_size)
    target = target_root / main.name
    action = _safe_link_or_copy(main, target)
    return WireOutcome(
        ok=True, runtime="whispercpp",
        detail=f"whisper.cpp 已 {action} 到 {target}",
        bin_path=str(target),
    )


def _wire_comfyui(model_path: Path, capability: str) -> WireOutcome:
    """ComfyUI: 按 capability 推断子目录(checkpoints / vae / upscale_models)。"""
    sub = {
        "text-to-image": "checkpoints",
        "t2i": "checkpoints",
        "text-to-video": "checkpoints",  # SVD 也走 checkpoints/
        "t2v": "checkpoints",
        "image-embedding": "clip_vision",
        "clip": "clip_vision",
    }.get(capability, "checkpoints")
    target_root = _comfyui_models_dir() / sub
    target = target_root / model_path.name
    action = _safe_link_or_copy(model_path, target)
    return WireOutcome(
        ok=True, runtime="comfyui",
        detail=f"ComfyUI 已 {action} 到 {target}",
        comfyui_subdir=sub,
        comfyui_path=str(target),
    )


def _wire_funasr(model_path: Path, capability: str) -> WireOutcome:
    """FunASR / Piper / CosyVoice / Paddle/RapidOCR / SBERT: 走 HF cache 即可。

    它们要么用 modelscope hub (但 modelscope 也尊重 ``MODELSCOPE_CACHE`` env,
    我们已在 mirror 切换时设置),要么直接从用户给的 ``--model_dir`` 加载。
    给一个 HF cache 软链通常就够。
    """
    out = _wire_hf_cache(model_path, capability)
    out.runtime = "funasr"
    return out


# ---------------------------------------------------------------------------
# 路径配置
# ---------------------------------------------------------------------------

def _chayuan_data_root() -> Path:
    return Path(os.environ.get("CHAYUAN_DATA") or os.environ.get("CHAYUAN_ROOT")
                or os.path.expanduser("~/.chayuan"))


def _llamacpp_models_dir() -> Path:
    p = _chayuan_data_root() / "vendor-data" / "llamacpp" / "models"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _whispercpp_models_dir() -> Path:
    p = _chayuan_data_root() / "vendor-data" / "whispercpp" / "models"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _comfyui_models_dir() -> Path:
    p = _chayuan_data_root() / "vendor-data" / "comfyui" / "models"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _read_repo_id_from_manifest(model_path: Path) -> Optional[str]:
    """从 ``manifest.json`` 读 ``repo_id``;modelmgr.verifier 写的格式。"""
    mf = model_path / "manifest.json"
    if not mf.is_file():
        return None
    try:
        import json

        return json.loads(mf.read_text(encoding="utf-8")).get("repo_id")
    except Exception:  # noqa: BLE001
        return None


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

WireFn = Callable[[Path, str], WireOutcome]


_WIRE_TABLE: Dict[str, WireFn] = {
    "ollama": _wire_ollama,
    "vllm": _wire_vllm,
    "infinity": _wire_infinity,
    "llamacpp": _wire_llamacpp,
    "llama-cpp": _wire_llamacpp,
    "whispercpp": _wire_whispercpp,
    "whisper-cpp": _wire_whispercpp,
    "comfyui": _wire_comfyui,
    "funasr": _wire_funasr,
    "piper": _wire_funasr,
    "cosyvoice": _wire_funasr,
    "voxcpm2": _wire_funasr,        # VoxCPM 2 (TTS) 走通用 modality wrapper 路径
    "rapidocr": _wire_funasr,
    "paddleocr": _wire_funasr,
    "hf-cache": _wire_hf_cache,
}


def wire(model_path: str, capability: str, target_runtime: str) -> WireOutcome:
    """统一入口:按 ``target_runtime`` 分派到具体实现。

    返回 :class:`WireOutcome`;调用方(lifecycle)按 ``ok`` 决定下一步。
    """
    fn = _WIRE_TABLE.get(target_runtime.lower())
    if fn is None:
        return WireOutcome(
            ok=False, runtime=target_runtime,
            detail=f"未知运行时: {target_runtime};受支持: {sorted(_WIRE_TABLE)}",
        )
    p = Path(model_path)
    if not p.exists():
        return WireOutcome(
            ok=False, runtime=target_runtime,
            detail=f"模型路径不存在: {model_path}",
        )
    try:
        return fn(p, capability)
    except Exception as e:  # noqa: BLE001
        logger.exception("wire %s failed", target_runtime)
        return WireOutcome(
            ok=False, runtime=target_runtime,
            detail=f"wire {target_runtime} 抛异常: {type(e).__name__}: {e}",
        )


# ---------------------------------------------------------------------------
# 注入到 lifecycle
# ---------------------------------------------------------------------------

def install_into_lifecycle() -> None:
    """让 lifecycle WIRE 阶段调用本模块的 :func:`wire`。

    在进程启动早期(``server_app.startup``)调用一次即可。如果 lifecycle 还没
    import 也没事,本函数 import 失败时只 warn。
    """
    try:
        from chayuan_modelmgr.lifecycle import WireOutcome as _LcOutcome
        from chayuan_modelmgr.lifecycle import register_wire_impl

        def _adapter(model_path: str, capability: str, target_runtime: str) -> object:
            out = wire(model_path, capability, target_runtime)
            # 转成 lifecycle.WireOutcome 类型
            return _LcOutcome(
                ok=out.ok, runtime=out.runtime,
                detail=out.detail, extra=out.extra,
            )

        register_wire_impl(_adapter)
        logger.info("framework_wiring installed into lifecycle")
    except Exception as e:  # noqa: BLE001
        logger.warning("framework_wiring not installed: %s", e)


__all__ = [
    "WireOutcome",
    "install_into_lifecycle",
    "wire",
]
